// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIfeWmhFuQPxt3KaCccWyL_cKlGPzXHaI',
    appId: '1:154127844457:web:7fc0dc55309837205b0ef8',
    messagingSenderId: '154127844457',
    projectId: 'musicapp-8b278',
    authDomain: 'musicapp-8b278.firebaseapp.com',
    storageBucket: 'musicapp-8b278.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGhzJy5w0LD5_H9C6tlhIBTaL2MCuGLfc',
    appId: '1:154127844457:android:b4910297f216cf665b0ef8',
    messagingSenderId: '154127844457',
    projectId: 'musicapp-8b278',
    storageBucket: 'musicapp-8b278.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtFIW_-ok2zZ5Nv_LWvMulXLOhO0gv5-Q',
    appId: '1:154127844457:ios:290d42c4c9c195795b0ef8',
    messagingSenderId: '154127844457',
    projectId: 'musicapp-8b278',
    storageBucket: 'musicapp-8b278.firebasestorage.app',
    iosBundleId: 'com.example.flutterTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtFIW_-ok2zZ5Nv_LWvMulXLOhO0gv5-Q',
    appId: '1:154127844457:ios:290d42c4c9c195795b0ef8',
    messagingSenderId: '154127844457',
    projectId: 'musicapp-8b278',
    storageBucket: 'musicapp-8b278.firebasestorage.app',
    iosBundleId: 'com.example.flutterTraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIfeWmhFuQPxt3KaCccWyL_cKlGPzXHaI',
    appId: '1:154127844457:web:c36d7205478d1b035b0ef8',
    messagingSenderId: '154127844457',
    projectId: 'musicapp-8b278',
    authDomain: 'musicapp-8b278.firebaseapp.com',
    storageBucket: 'musicapp-8b278.firebasestorage.app',
  );
}
